const swaggerAutogen = require('swagger-autogen')()

const outputFile = './swagger_output.json'
const endpointsFiles = ['./server.js']

const doc = {
    info: {
        version: "1.0.0",
        title: "MyMe API",
        description: "Documentation automatically generated by the <b>swagger-autogen</b> module."
    },
    host: "localhost:8080",
    basePath: "/",
    schemes: ['http', 'https'],
    consumes: ['application/json'],
    produces: ['application/json'],
    tags: [
        {
            "name": "User",
            "description": "Endpoints"
        }
    ],
    securityDefinitions: {
        api_key: {
            type: "apiKey",
            name: "x-access-token",
            in: "header"
        }
    },
    definitions: {
        User: {
            id: 1,
            username: "daniel",
            email:"daniel@gmail.com",
            is_admin:true,
            password:"12345678",
            phone_number:12323242,
            gender:"male",
            birth_date:"1999-12-12",
            createdAt:"2021-05-12T15:00:00.000Z",
            updatedAt:"2021-05-12T15:00:00.000Z"
        },
        AddUser: {
            $username: "daniel",
            $email:"daniel@gmail.com",
            $is_admin:true,
            $password:"12345678",
            $phone_number:12323242,
        },
        UpdateUser: {
            $username: "daniel",
            $email:"daniel@gmail.com",
            $is_admin:true,
            $password:"12345678",
            $phone_number:12323242,
            $gender:"male",
            $birth_date:"1999-12-12",
        },
        LoginUser: {
            $email:"daniel@gmail.com",
            $password:"12345678",
        },
        Answer: {
            id: 1,
            answers: {
                question_1: 1,
                question_2: 2
            },
            score: 5,
            createdAt: "2023-06-08T15:37:12.025Z",
            updatedAt: "2023-06-08T15:37:12.025Z",
            user_id: 1
        },
        AddAnswer: {
            $answers: {
                question_1: 1,
                question_2: 2
            },
            $score: 5,
            $user_id: 1
        },
        UpdateAnswer: {
            $answers: {
                question_1: 1,
                question_2: 2
            },
            $score: 5,
            $user_id: 1
        },
        Question: {
            id: 1,
            question: "How are you?",
            createdAt: "2023-06-08T15:37:12.025Z",
            updatedAt: "2023-06-08T15:37:12.025Z"
        },
        AddQuestion: {
            $question: "How are you?"
        },
        UpdateQuestion: {
            $question: "How are you?"
        },
        Article: {
            id: 1,
            title: "How to be happy",
            description: "This is a description",
            content: "Be happy",
            user_id: 1,
            images:"https://assets.kompasiana.com/statics/files/14097150691406209980.jpg?t=o&v=700?t=o&v=770",
        },
        AddArticle: {
            $title: "How to be happy",
            $description: "This is a description",
            $content: "Be happy",
            $user_id: 1,
            $images:"https://assets.kompasiana.com/statics/files/14097150691406209980.jpg?t=o&v=700?t=o&v=770",
        },
        UpdateArticle: {
            $title: "How to be happy",
            $description: "This is a description",
            $content: "Be happy",
            $user_id: 1,
            $images:"https://assets.kompasiana.com/statics/files/14097150691406209980.jpg?t=o&v=700?t=o&v=770",
        },

    }  
}

swaggerAutogen(outputFile, endpointsFiles, doc).then(()=> {
    require('./server.js')
})